listSuccess:
  stylesheets:
    - /sfDoctrineMooDooPlugin/css/generator.list.css
formSuccess:
  stylesheets:
    - /sfDoctrineMooDooPlugin/css/generator.edit.css
    - jquery.Jcrop.css
  javascripts:
    - tiny_mce/tiny_mce.js
    - JCrop/jquery.min.js
    - JCrop/jquery.Jcrop.min.js

